routes/web.php
<?php
use App\Http\Controllers\PostsController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', 'PostsController@main');
//Route::get('/', ['as' => 'main', 'uses' => 'PostsController@main']);
Route::get('/', [PostsController::class, 'main']);
Auth::routes();
/*Route::get('/', function () {
	return view('welcome');
});*/

/**
 * para el control y modificación de información de usuario*/
Route::group(['middleware' => 'auth'], function () {
	//Route::resource('/account', [UsersController::class, 'profile']);

	Route::resource('posts', PostsController::class);

	Route::post('/page', [PostsController::class, 'load']);
	Route::get('/page', ['as' => 'posts.post', 'uses' => [HomeController::class,'load']]);

	Route::get('/add', [PostsController::class, 'create']);
	Route::post('/postinsert', [PostsController::class, 'ajaxAdd']);
	Route::get('/account', [UsersController::class, 'index']);
	Route::post('/loadimage', [UsersController::class, 'loadImage']);
	Route::post('/accountupdate', [UsersController::class, 'upProfile']);
	Route::post('/upimage', [UsersController::class, 'upImage']);
	Route::post('/uppassword', [UsersController::class, 'upPassword']);

	Route::post('/postupdate', [PostsController::class, 'ajaxUpdate']);
	Route::post('/postdelete', [PostsController::class, 'ajaxDelete']);
});

/*Route::group(['middleware' => 'auth'], function () {
	Route::get('/post/{slug?}', ['as' => 'posts.post', 'uses' => [PostsController::class, 'view']]);
	Route::get('/add', [PostsController::class, 'create']);
	Route::get('/postinsert', [PostsController::class, 'ajaxAdd']);
	Route::post('/postinsert', [PostsController::class, 'ajaxAdd']);
	Route::get('/postupdate', [PostsController::class, 'ajaxUpdate']);
	
	
});*/

Route::get('/post/{slug}', [HomeController::class, 'view']);
//Route::get('/post/{slug}', [PostController::class, 'show']);
//Route::get('/post/{slug}', ['as' => 'posts.view', 'uses' => [HomeController::class,'view']]);

//Route::get('/{slug?}', ['as' => 'home.view', 'uses' => 'HomeController@view']);

//Auth::routes();

/*Route::get('/home', [App\Http\Controllers\HomeController::class, 'index']);


Route::get('admin/home', [HomeController::class, 'adminHome'])->name('admin.home')->middleware('is_admin');

Route::get('posts',['as'=>'posts.index','uses'=>'PostsController@index']);*/

app/Models/Posts.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Posts extends Model
{
    //use HasFactory;
    protected $fillable = ['title', 'desc', 'slug', 'files', 'image', 'status', 'user_id'];
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Posts;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Auth;

class PostsController extends Controller
{
    /**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index(){
		$userId = Auth::user()->id;
		$posts = Posts::where(['user_id' => $userId])->get();
		return view('posts.list', ['posts' => $posts]);
	}

	public function main(){
		$data = Posts::where('status', '=', 'publicado')
					->orderBy('created_at', 'desc')
					->paginate(9);
		return view('main', compact('data'));
	}

	public function ajaxAdd(Request $request){
		$userId 			= Auth::user()->id;
		$input 				= $request->input();
		$input['user_id'] 	= $userId;
		$input['slug'] 		= $this->slugify($this->get_words($input['title'], 5));
		$input['files'] = 'files/'.$this->randomStr(8).'/';

		$path = public_path().'/'.$input['files'];
		if(!File::exists($path)) {
			File::makeDirectory($path, $mode = 0777, true, true);
		}
		if($request->hasfile('image')){
			foreach($request->file('image') as $image){
				$imageName = $input['image'] 	= $this->randomStr(4).'-'.$this->randomStr(4).'.'.$image->getClientOriginalExtension();
				$image->move(public_path().'/'.$input['files'], $imageName);
				$insert['image'] 	= "$imageName";
			}
		}
		$postStatus 		= Posts::create($input);
		if ($postStatus) {
			$msg = array("type" => 'success',
						"id" 	=> $postStatus->id,
						"url" 	=> route('posts.edit', $postStatus->id),
						"icon" 	=> 'fa fa-check',
						"msg" 	=> 'Registro agregado correctamente.');
		} else {
			$msg = array("type" => 'danger',
						"icon" 	=> 'fa fa-times',
						"msg" 	=> 'Error con la base de datos.');
		}

		return response()->json($msg);
	}

	public function ajaxUpdate(Request $request){
		$input 		= $request->input();
		$userId 	= Auth::user()->id;
		$post 		= Posts::find($input['id']);
		if (!$post) {
			return redirect('posts')->with('error', 'Registro no encoentrado.');
		}
		$input['user_id'] 	= $userId;
		$input['slug'] 		= $this->slugify($this->get_words($input['title'], 5)).'-'.$input['id'];
		$postStatus 		= $post->update($input);
		if ($postStatus) {
			$msg = array("type" => 'success',
						"icon" 	=> 'fa fa-check',
						"msg" 	=> 'Registro actualizado correctamente.');
		} else {
			$msg = array("type" => 'danger',
						"icon" 	=> 'fa fa-times',
						"msg" 	=> 'Error con la base de datos.');
		}

		return response()->json($msg);
	}

	public function ajaxDelete(Request $request){
		$input 		= $request->input();
		$userId 	= Auth::user()->id;
		$post 		= Posts::find($input['id']);
		
		$postDelStatus = $post->delete();
		if ($postDelStatus) {
			$msg = array("type" => 'success',
						"icon" 	=> 'fa fa-check',
						"msg" 	=> 'Registro elimiando correctamente.');
		} else {
			$msg = array("type" => 'danger',
						"icon" 	=> 'fa fa-exclamation-circle',
						"msg" 	=> 'Error con la base de datos.');
		}

		return response()->json($msg);
	}

	public function load(Request $request){
		$userId 			= Auth::user()->id;
		$input['user_id'] 	= $userId;

		$data['page'] 		= ($request->input('page')) 	? $request->input('page'): 1;
		$data['order'] 		= ($request->input('order')) 	? $request->input('order'): "desc";
		$data['order_by'] 	= ($request->input('order_by')) ? $request->input('order_by'): "id";
		$data['search'] 	= ($request->input('search')) 	? trim($request->input('search')) : "";
		$data['per_page'] 	= ($request->input('limite')) 	? $request->input('limite'): 10;
		$data['filter'] 	= ($request->input('filter')) 	? $request->input('filter')-1: 1;
		$data['offset'] 	= ($data['page'] - 1) * $data['per_page'];
		$data['adyacentes'] = 2;

		$total = DB::table('posts')
			->join('users', 'users.id', '=', 'posts.user_id')
			->select('posts.*', 'users.*')
			->where('posts.user_id', '=', $userId)
			->where('title', 'like', '%'.$data['search'].'%')
			->count();

		$results = DB::table('posts')
			->join('users', 'users.id', '=', 'posts.user_id')
			->select('posts.*')
			->where('posts.user_id', '=', $userId)
			->where('title', 'like', '%'.$data['search'].'%')
			->offset($data['offset'])
			->limit($data['per_page'])
			->orderBy($data['order_by'], $data['order'])
			->get();

		$total_pages = ceil($total/$data['per_page']);
		$reload 			= url('/page');
		$response['total']  = "Total de resultados: ".$total;

		$response['data'] 	= "";
		if ($total>0) {
			$response['data'] .= '<table class="table table-bordered table-hover">
				<thead class="thead-light">
					<tr class="row-link">
						<th data-field="id" class="th-link w-10"><i class="far fa-sort"></i> #</th>
						<th data-field="title" class="th-link"><i class="far fa-sort"></i> Nombre</th>
						<th data-field="status" class="w-15 th-link text-center"><i class="far fa-sort"></i> Estado</th>
						<th class="w-15 text-center">Acción</th>
					</tr>
				</thead>
				<tbody>';
			foreach ($results as $post) {
				$response['data'] .='<tr>
							<th>
								'.$post->id.'
							</th>
							<td>
								<a href="'.url('/post/'.$post->slug).'">'.$post->title.'</a>
							</td>
							<td>
								<center>'.$post->status.'</center>
							</td>
							<td class="text-center">
								<a href="'.route('posts.edit', $post->id).'" class="btn btn-success btn-sm">
									<svg class="bi bi-check2-square" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
										<path fill-rule="evenodd" d="M15.354 2.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3-3a.5.5 0 1 1 .708-.708L8 9.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
										<path fill-rule="evenodd" d="M1.5 13A1.5 1.5 0 0 0 3 14.5h10a1.5 1.5 0 0 0 1.5-1.5V8a.5.5 0 0 0-1 0v5a.5.5 0 0 1-.5.5H3a.5.5 0 0 1-.5-.5V3a.5.5 0 0 1 .5-.5h8a.5.5 0 0 0 0-1H3A1.5 1.5 0 0 0 1.5 3v10z"/>
									</svg> <span class="d-none d-md-inline">Editar</span>
								</a> 
								<button type="button" id="btn-del-'.$post->id.'" name="btn-del-'.$post->id.'" class="btn btn-danger btn-sm mdl-del-reg" data-toggle="modal" data-target="#mdl-del-reg" data-idreg="'.$post->id.'" data-nomreg="'.$post->title.'">
									<svg class="bi bi-trash" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
										<path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
										<path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
									</svg>
								</button>
							</td>
						</tr>';
			}
			$response['data'] .= '</tbody></table>';
			$response['data'] .= '<span class="pull-right">'.$this->paginate($reload, $data['page'], $total_pages, $data['adyacentes'], 'load').'</span>';
		}else{
			$response['data'] 	= '<div class="alert alert-info text-center" role="alert"><i class="fas fa-search"></i> Búsqueda sin resultados.</div>';
		}
		
		return response()->json($response);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		return view('posts.add');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request){
		$userId 			= Auth::user()->id;
		$input 				= $request->input();
		$input['user_id'] 	= $userId;
		$postStatus 		= Posts::create($input);
		if ($postStatus) {
			$request->session()->flash('success', 'Todo successfully added');
		} else {
			$request->session()->flash('error', 'Oops something went wrong, Todo not saved');
		}
		return redirect('posts');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function show($id)
	{
		$userId = Auth::user()->id;
		$post = Posts::where(['user_id' => $userId, 'id' => $id])->first();
		if (!$post) {
			return redirect('todo')->with('error', 'Todo not found');
		}
		return view('posts.view', ['todo' => $post]);
	}

	public function view($slug){
		$userId 	= Auth::user()->id;
		$post 		= Posts::where(['user_id' => $userId, 'slug' => $slug])->first();
		if (!$post) {
			return redirect('todo')->with('error', 'Registro no encontrado, por favor revise.');
		}
		return view('posts.view', ['todo' => $post]);
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id)
	{
		$userId = Auth::user()->id;
		$post = Posts::where(['user_id' => $userId, 'id' => $id])->first();
		if ($post) {
			return view('posts.edit', [ 'todo' => $post ]);
		} else {
			return redirect('posts')->with('error', 'Todo not found');
		}
	}
	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request, $id){
		$userId 	= Auth::user()->id;
		$post 		= Posts::find($id);
		$input 		= $request->input();
		if (!$post) {
			return redirect('posts')->with('danger', 'Regitro no encontrado.');
		}

		$path = public_path().'/'.$post->files;
		if(!File::exists($path)) {
			File::makeDirectory($path, $mode = 0777, true, true);
		}
		if($request->hasfile('image')){
			foreach($request->file('image') as $image){
				$imageName = $input['image'] 	= $this->randomStr(4).'-'.$this->randomStr(4).'.'.$image->getClientOriginalExtension();
				$image->move(public_path().'/'.$post->files, $imageName);
				$insert['image'] 	= "$imageName";
			}
			$delImg 	= public_path().'/'.$post->files.$post->image;
			if(File::exists($delImg)){
				File::delete($delImg);
			}
		}

resources/views/posts/edit.blade.php
@extends('layouts.app')
@section('content')
@section('title', 'Editar')
<script>
	var base_url = "{{url('/')}}";
</script>
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<nav aria-label="breadcrumb">
				<ol class="breadcrumb">
					<li class="breadcrumb-item">
						<a href="{{url('/')}}"><svg class="bi bi-house-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
							<path fill-rule="evenodd" d="M8 3.293l6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6zm5-.793V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
							<path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"/>
						</svg> Inicio</a>
					</li>
					<li class="breadcrumb-item">
						<a href="{{url('posts')}}">
							<svg class="bi bi-list-task" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
								<path fill-rule="evenodd" d="M2 2.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5V3a.5.5 0 0 0-.5-.5H2zM3 3H2v1h1V3z"/>
								<path d="M5 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM5.5 7a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 4a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9z"/>
								<path fill-rule="evenodd" d="M1.5 7a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5V7zM2 7h1v1H2V7zm0 3.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5H2zm1 .5H2v1h1v-1z"/>
							</svg> Registros</a>
					</li>
					<li class="breadcrumb-item active" aria-current="page">
						<span><svg class="bi bi-check2-square" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
							<path fill-rule="evenodd" d="M15.354 2.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3-3a.5.5 0 1 1 .708-.708L8 9.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
							<path fill-rule="evenodd" d="M1.5 13A1.5 1.5 0 0 0 3 14.5h10a1.5 1.5 0 0 0 1.5-1.5V8a.5.5 0 0 0-1 0v5a.5.5 0 0 1-.5.5H3a.5.5 0 0 1-.5-.5V3a.5.5 0 0 1 .5-.5h8a.5.5 0 0 0 0-1H3A1.5 1.5 0 0 0 1.5 3v10z"/>
						</svg> Edición </span>
					</li>
				</ol>
			</nav>
		</div>
	</div>
	<div class="row justify-content-center">
		<div class="col-md-12">
			@if (session('success'))
				<script type="text/javascript">
					$(document).ready(function() {
						notify_msg("fa fa-check", " ", "{{session('success')}}", "#", "success");
					});
				</script>
			@endif
			@if (session('danger'))
				<script type="text/javascript">
					$(document).ready(function() {
						notify_msg("fa fa-times", " ", "{{session('danger')}}", "#", "danger");
					});
				</script>
			@endif
			<form action="{{route('posts.update', $todo->id)}}" method="POST" enctype="multipart/form-data" accept-charset="UTF-8">
			<!--form id="form-update" name="form-update" action="" method="POST"-->
				@csrf
				@method('PUT')
				<input type="hidden" class="form-control" id="id" name="id" value="{{$todo->id}}" readonly="">
				<div class="row">
					<div class="col-md-3">
						<div class="card border">
							<div class="box-img-evt">
								<a href="{{($todo->image!='' && file_exists(public_path($todo->files.$todo->image)) ? asset('public/'.$todo->files.$todo->image): asset('public/images/default.svg'))}}" data-lightbox="img-gallery-1" data-title="Imagen">
									<img class="img-fluid" src="{{($todo->image!='' && file_exists(public_path($todo->files.$todo->image)) ? asset('public/'.$todo->files.$todo->image): asset('public/images/default.svg'))}}" alt="Imagen de perfil"/>
								</a>
								<ul class="icon">
									<li>
										<a href="{{($todo->image!=''?asset('public/'.$todo->files.$todo->image): asset('public/images/default.svg'))}}" class="btn btn-primary btn-sm" data-lightbox="img-gallery-2" data-title="Imagen">
											<svg class="bi bi-eye" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
												<path fill-rule="evenodd" d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.134 13.134 0 0 0 1.66 2.043C4.12 11.332 5.88 12.5 8 12.5c2.12 0 3.879-1.168 5.168-2.457A13.134 13.134 0 0 0 14.828 8a13.133 13.133 0 0 0-1.66-2.043C11.879 4.668 10.119 3.5 8 3.5c-2.12 0-3.879 1.168-5.168 2.457A13.133 13.133 0 0 0 1.172 8z"/>
												<path fill-rule="evenodd" d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
											</svg>
										</a>
									</li>
								</ul>
							</div>
						</div>
						<div class="custom-file mt-2">
							<input type="file" class="custom-file-input" id="files-all" name="image[]" accept=".png, .jpg, .jpeg">
							<label class="custom-file-label" for="files-all" data-browse="Elegir">
								Seleccionar archivos...
							</label>
						</div>
					</div>
					<div class="col-md-9">
						<div class="form-group input-group">
							<span class="has-float-label">
								<input type="text" class="form-control" id="title" name="title" value="{{$todo->title}}" required="">
								<label for="title">Título:</label>
							</span>
						</div>
						<div class="form-group input-group">
							<span class="has-float-label">
								<textarea name="desc" class="form-control" id="desc" rows="5" required="">{{ $todo->desc}}</textarea>
								<label for="desc">Descripción:</label>
							</span>
						</div>
						<div class="form-group input-group">
							<span class="has-float-label">
								<select class="form-control custom-select" id="status" name="status" required="">
									<option value="pendiente" @if ($todo->status == 'pendiente') selected="" @endif>Pendiente</option>
									<option value="publicado" @if ($todo->status == 'publicado') selected="" @endif>Publicado</option>
								</select>
								<label for="status">Estado:</label>
							</span>
						</div>
					</div>
				</div>
				<button id="btn-update" name="btn-update" type="submit" class="btn btn-primary float-right">
					<svg class="bi bi-check2" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
						<path fill-rule="evenodd" d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
					</svg> Actualizar
				</button>
			</form>
		</div>
	</div>
</div>
<script src="{{asset('public/js/ajxtodoapp.js')}}" defer></script>
@endsection

resources/views/posts/list.blade.php
@extends('layouts.app')
@section('content')
@section('title', 'Registros')
<script>
	var base_url = "{{url('/')}}";
</script>

@include('posts.modals')

<div class="container">
	<div class="row">
		<div class="col-md-12">
			@if (session('success'))
				<script type="text/javascript">
					$(document).ready(function() {
						notify_msg("fa fa-check", " ", "{{session('success')}}", "#", "success");
					});
				</script>
			@endif
			@if (session('danger'))
				<script type="text/javascript">
					$(document).ready(function() {
						notify_msg("fa fa-times", " ", "{{session('danger')}}", "#", "danger");
					});
				</script>
			@endif
			<nav aria-label="breadcrumb">
				<ol class="breadcrumb">
					<li class="breadcrumb-item">
						<a href="{{url('/')}}"><i class="fa fa-home"></i> Inicio</a>
					</li>
					<li class="breadcrumb-item active" aria-current="page">
						 Registros
					</li>
				</ol>
			</nav>
		</div>
	</div>

	<div class="form-row mt-2 mb-1">
		<div class="col-lg-1 col-md-2 col-sm-2 col-2">
			<div class="dropdown-limit input-group">
				<button type="button" class="btn btn-primary dropdown-toggle btn-block" data-toggle="dropdown">
					<span class="d-none d-md-inline-block fa fa-list-ol"></span> <span id="spn-show-list">10</span>
				</button>
				<div id="select-list" class="dropdown-menu">
					<a class="dropdown-item" href="#" data-total="10">10</a>
					<a class="dropdown-item" href="#" data-total="20">20</a>
					<a class="dropdown-item" href="#" data-total="30">30</a>
					<a class="dropdown-item" href="#" data-total="40">40</a>
					<a class="dropdown-item" href="#" data-total="50">50</a>
				</div>
			</div>
		</div>						

		<div class="col-lg-9 col-md-8 col-sm-8 col-8">
			<form method="post" enctype="multipart/form-data" accept-charset="utf-8" id="form-search" name="form-search">
				<div class="input-group">
					<div class="dropdown-edo input-group-prepend">
						<button id="btn-search-on" type="button" class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown">
							<i id="i-icon-act" class="fas fa-check"></i> <span id="spn-desc-act" class="d-none d-md-inline-block">Activos</span>
						</button>
						<div class="dropdown-menu">
							<a class="dropdown-item" href="#" data-desc="Todos" data-icon="fas fa-list-ol" data-edo="3">
								<i class="fas fa-list-ol"></i> Todos
							</a>
							<a class="dropdown-item" href="#" data-desc="Activos" data-icon="fas fa-check" data-edo="2">
								<i class="fas fa-check"></i> Activos
							</a>
							<a class="dropdown-item" href="#" data-desc="Inactivos" data-icon="fas fa-times" data-edo="1">
								<i class="fas fa-times"></i> Inactivos
							</a>
						</div>
					</div>
					<input type="text" class="form-control txt-search-nv" name="txt-search" id="txt-search" placeholder="Buscar...">
					<div class="input-group-append">
						<button type="submit" class="btn btn-search-nav" name="btn-search" id="btn-search">
							<i class="fal fa-search"></i>
						</button>
					</div>
				</div>
			</form>
		</div>
		<div class="colg-lg-1 col-md-2 col-sm-2 col-2">
			<button class="btn btn-block btn-success btn-open-mdl" title="Agregar" data-toggle="modal" data-target="#mdl-add-reg">
				<svg class="bi bi-plus-circle" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
					<path fill-rule="evenodd" d="M8 3.5a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-.5.5H4a.5.5 0 0 1 0-1h3.5V4a.5.5 0 0 1 .5-.5z"/>
					<path fill-rule="evenodd" d="M7.5 8a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1H8.5V12a.5.5 0 0 1-1 0V8z"/>
					<path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
				</svg> <span class="d-none d-md-inline">Agregar</span>
			</button>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12 text-right">
			<h5 id="h5-cnt-total"></h5>
		</div>
	</div>
	<div class="row">
		<div id="div-cnt-load" class="col-md-12"></div>
	</div>
</div>
<script src="{{asset('public/js/ajxtodoapp.js')}}" defer></script>
<script type="text/javascript">
	$(document).ready(function() {
		load(1);
	});
</script>

@endsection